### ISSUE TITLE
Does this system ensure no freak trades happen ? 

### ISSUE THREAD

**Issue by rohitsakala** [aakashlpin/kha-ching#56]

**Comment by aakashlpin** [comment]
We have support for both SL-L and SL-M orders. 

SL-L orders do not guarantee execution and are hence monitored in a way that if the order stays ```Open``` for more than 30seconds after getting triggered, the algorithm would modify the order type from ```Limit``` to ```Market```

While, SL-L orders are live, the modification of order type from ```Limit``` to ```Market``` is still under testing and will be rolled out in the coming week.

**Comment by rohitsakala** [comment]
Thanks for the info.
